/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmlc3_free: (a: number, b: number) => void;
export const analyze_completions: (a: number, b: number, c: number, d: number) => any;
export const analyze_definition: (a: number, b: number, c: number, d: number) => any;
export const analyze_diagnostics: (a: number, b: number) => any;
export const analyze_hover: (a: number, b: number, c: number, d: number) => any;
export const analyze_references: (a: number, b: number, c: number, d: number) => any;
export const analyze_symbols: (a: number, b: number) => any;
export const analyze_tokens: (a: number, b: number) => any;
export const assemble: (a: number, b: number) => any;
export const assemble_to_bytes: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmlc3_cond_str: (a: number) => [number, number];
export const wasmlc3_load: (a: number, b: number, c: number, d: number) => void;
export const wasmlc3_load_bytes: (a: number, b: number, c: number) => [number, number];
export const wasmlc3_mem: (a: number, b: number) => number;
export const wasmlc3_mem_slice: (a: number, b: number, c: number) => [number, number];
export const wasmlc3_n: (a: number) => number;
export const wasmlc3_new: () => number;
export const wasmlc3_p: (a: number) => number;
export const wasmlc3_pc: (a: number) => number;
export const wasmlc3_reg: (a: number, b: number) => number;
export const wasmlc3_regs: (a: number) => [number, number];
export const wasmlc3_reset: (a: number) => void;
export const wasmlc3_run: (a: number) => any;
export const wasmlc3_set_input: (a: number, b: number) => void;
export const wasmlc3_set_mem: (a: number, b: number, c: number) => void;
export const wasmlc3_set_pc: (a: number, b: number) => void;
export const wasmlc3_set_reg: (a: number, b: number, c: number) => void;
export const wasmlc3_step: (a: number) => any;
export const wasmlc3_z: (a: number) => number;
export const init: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
